version: '3.8'

services:
  oauth2-provider:
    build: ../oauth2
    ports:
      - "8000:8000"
    volumes:
      - ../oauth2:/app
    environment:
      - DEBUG=True
    networks:
      - oauth-network

  oauth2-client:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - OAUTH2_PROVIDER_URL=http://oauth2-provider:8000/oauth2
      - OAUTH2_CLIENT_ID=your_client_id
      - OAUTH2_CLIENT_SECRET=your_client_secret
      - OAUTH2_REDIRECT_URI=http://localhost:8080/oauth2/callback
      - DEBUG=True
      - SECRET_KEY=your_django_secret_key
    depends_on:
      - oauth2-provider
    networks:
      - oauth-network

networks:
  oauth-network:
    driver: bridge 